---
# tasks file for sage

- name: Set some local variables
  set_fact:
    archive_path: '/tmp/sage-{{ sage_version }}-Ubuntu_20.04-x86_64.tar.bz2'

- name: Download sage
  get_url:
    url: 'http://ftp.yz.yamagata-u.ac.jp/pub/math/sage/linux/64bit/{{ tool_path }}/sage-{{ sage_version }}-Ubuntu_20.04-x86_64.tar.bz2'
    dest: '{{ archive_path }}'

- name: Unarchive sage
  ansible.builtin.unarchive:
    src: '{{ archive_path }}'
    dest: '{{ tool_path }}/SageMath/sage'

- name: Remove archive
  ansible.builtin.file:
    path: '{{ archive_path }}'
    state: absent

- name: Create symbolic link
  ansible.builtin.file:
    src: '{{ tool_path }}/SageMath/sage'
    dest: /usr/bin/sage
    state: link


