- name: Install neovim
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ version }}/nvim.appimage"
    dest: "/usr/local/bin/nvim"
    mode: "0755"
- name: Add alternatives
  become: true
  ansible.builtin.shell:
    cmd: |
      update-alternatives --install /usr/bin/vi vi /usr/local/bin/nvim 60
      update-alternatives --install /usr/bin/vim vim /usr/local/bin/nvim 60
      update-alternatives --install /usr/bin/editor editor /usr/local/bin/nvim 60

