# tasks file for sagemath
- name: Check SageMath is installed
  ansible.builtin.shell: sage --version
  ignore_errors: true
  register: sage_install_check
- name: Finish if SageMath is installed
  ansible.builtin.meta: end_play
  when: sage_install_check.rc == 0
- name: Install SageMath
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    install_recommends: false
    autoclean: true
    autoremove: true
    name:
      - sagemath
