# tasks file for sagemath
- name: Check SageMath is installed
  ansible.builtin.shell: sage --version
  ignore_errors: true
  register: sage_install_check
- name: Finish if SageMath is installed
  ansible.builtin.meta: end_play
  when: sage_install_check.rc == 0
- name: Install SageMath
  become: true
  ansible.builtin.apt:
    install_recommends: false
    autoclean: true
    autoremove: true
    name:
      - sagemath
      - bc
      - binutils
      - bzip2
      - ca-certificates
      - cliquer
      - cmake
      - curl
      - ecl
      - eclib-tools
      - fflas-ffpack
      - g++
      - gcc
      - gengetopt
      - gfan
      - gfortran
      - glpk-utils
      - gmp-ecm
      - lcalc
      - libatomic-ops-dev
      - libboost-dev
      - libbraiding-dev
      - libbrial-dev
      - libbrial-groebner-dev
      - libbz2-dev
      - libcdd-dev
      - libcdd-tools
      - libcliquer-dev
      - libcurl4-openssl-dev
      - libec-dev
      - libecm-dev
      - libffi-dev
      - libflint-arb-dev
      - libflint-dev
      - libfplll-dev
      - libfreetype6-dev
      - libgc-dev
      - libgd-dev
      - libgf2x-dev
      - libgiac-dev
      - libgivaro-dev
      - libglpk-dev
      - libgmp-dev
      - libgsl-dev
      - libhomfly-dev
      - libiml-dev
      - liblfunction-dev
      - liblinbox-dev
      - liblrcalc-dev
      - liblzma-dev
      - libm4ri-dev
      - libm4rie-dev
      - libmpc-dev
      - libmpfi-dev
      - libmpfr-dev
      - libncurses5-dev
      - libntl-dev
      - libopenblas-dev
      - libpari-dev
      - libplanarity-dev
      - libppl-dev
      - libprimesieve-dev
      - libpython3-dev
      - libqhull-dev
      - libreadline-dev
      - librw-dev
      - libsingular4-dev
      - libsqlite3-dev
      - libssl-dev
      - libsuitesparse-dev
      - libsymmetrica2-dev
      - libz-dev
      - libzmq3-dev
      - m4
      - make
      - meson
      - nauty
      - ninja-build
      - openssl
      - palp
      - pari-doc
      - pari-elldata
      - pari-galdata
      - pari-galpol
      - pari-gp2c
      - pari-seadata
      - patch
      - perl
      - pkg-config
      - planarity
      - ppl-dev
      - python3
      - python3-distutils
      - python3-venv
      - singular
      - singular-doc

- name: Download a sage source
  get_url:
    url: "https://ftp.riken.jp/sagemath/src/sage-10.0.tar.gz"
    dest: "/tmp/sage-{{ sage.version }}.tar.gz"
    mode: '0644'

- name: Extract the tar file
  unarchive:
    src: "/tmp/sage-{{ sage.version }}.tar.gz"
    dest: "/opt"
    remote_src: true

- name: Change directory to the source
  command: "chdir=/opt/sage-{{ sage.version }}"

- name: Run ./configure
  command: ./configure

- name: Run make
  command: make -j$(nproc)

