---
- hosts: ctf
  user: ctf
  roles:
    - role: base
      vars:
        apt_repository: http://ftp.jaist.ac.jp/pub/Linux/ubuntu
        packages:
          - gcc
          - libfuse-dev
    - role: pyenv
      vars:
        path: '{{ ansible_env.HOME }}/.pyenv'
        versions:
          - 3.12.2
          - 2.7.18
        configure_opts: '--enable-shared'
        packages:
          - pwntools
          - pycryptodome
          - z3-solver
          - httpie
          - neovim
    - role: neovim
      vars:
        version: v0.9.5
          #    - role: burp
          #      vars:
          #        version: 2023.12.1.5
          #        path: '{{ ansible_env.HOME }}/tools/burpsuite_community'
    - role: goenv
      vars:
        path: '{{ ansible_env.HOME }}/.goenv'
        versions:
          - 1.22.0
    - role: rizin
      vars:
        version: v0.3.3
        path: '{{ ansible_env.HOME }}/tools/rzpm'
        url: 'https://github.com/rizinorg/rz-pm/releases/download/{{ version }}/rz-pm-linux-x86_64'
    - role: gdb
      vars:
        pwndbg:
          path: '{{ ansible_env.HOME }}/tools/pwndbg'
    - role: rust
      vars:
        packages:
          - vivid
          - zoxide
          - ropr
          - pwninit
    - role: rbenv
      vars:
        path: '{{ ansible_env.HOME }}/.rbenv'
        versions:
          - 3.3.0
    - role: patchelf
      vars:
        path: '{{ ansible_env.HOME }}/tools/patchelf'
    - role: sagemath
      vars:
        path: '{{ ansible_env.HOME }}/tools/sagemath'
        version: 10.2
