---
- hosts: ctf
  user: ctf
  roles:
    - role: base
      vars:
        apt_repository: http://ftp.jaist.ac.jp/pub/Linux/ubuntu
        packages:
          - gcc
    - role: pyenv
      vars:
        path: '{{ ansible_env.HOME }}/.pyenv'
        versions:
          - 3.12.1
          - 2.7.18
        configure_opts: '--enable-shared'
        packages:
          - pwntools
          - pycryptodome
          - z3-solver
    - role: burp
      vars:
        version: 2023.2.3
        path: '{{ ansible_env.HOME }}/tools/burpsuite_community'
    - role: goenv
      vars:
        path: '{{ ansible_env.HOME }}/.goenv'
        versions:
          - 1.21.6
    - role: radare2
      vars:
        path: '{{ ansible_env.HOME }}/tools/radare2'
    - role: gdb
      vars:
        pwndbg:
          path: '{{ ansible_env.HOME }}/tools/pwndbg'
    - role: rust
      vars:
        packages:
          - vivid
          - zoxide
          - ropr
    - role: rbenv
      vars:
        path: '{{ ansible_env.HOME }}/.rbenv'
        versions:
          - 3.2.2
    - role: patchelf
      vars:
        path: '{{ ansible_env.HOME }}/tools/patchelf'
    - role: sagemath
      vars:
        path: '{{ ansible_env.HOME }}/tools/sagemath'
        version: 10.2
