---
# tasks file for radare2
- name: Check radare2 is installed
  ansible.builtin.shell: . ~/.profile && which r2
  ignore_errors: true
  register: r2_install_check


- name: Install prerequisites
  become: yes
  apt:
    update_cache: true
    install_recommends: false
    pkg:
      - build-essential
      - ccache
      - cmake
      - bison
      - flex
      - pkg-config

- name: Clone radare2
  git:
    repo: https://github.com/radareorg/radare2.git
    dest: '{{ radare2.path }}'

- name: Install r2env
  shell: |
    . ~/.profile
    python -m pip install -U r2env
    pyenv rehash

- name: Add to .profile
  ansible.builtin.blockinfile:
    path: ~/.profile
    insertafter: EOF
    create: true
    marker: '# {mark} ANSIBLE MANAGED BLOCK [r2env]'
    block: |
      export R2ENV_PATH="${HOME}/.r2env"
      export PATH="${R2ENV_PATH}/bin:${PATH}"

- name: Install radare2
  shell: | 
    . ~/.profile
    r2env init
    r2env add radare2@git
    r2env use radare2@git
    r2env add r2ghidra@git
  when: r2_install_check.rc != 0
